# Generated by Django 4.2 on 2026-09-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=35)),
                ('salary', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
            ],
        ),
    ]
